name: Lint

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install pnpm packages
        run: pnpm install

      - name: Lint
        run: pnpm run lint
