name: Update importedGuns.json

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-importedguns:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute script
        id: roblox-luau-execution
        uses: grand-hawk/action-roblox-luau-execution@1.0.0
        with:
          roblox_api_key: ${{ secrets.ROBLOX_LUAU_EXECUTION_API_KEY }}
          universe_id: "3221676855"
          place_id: "8421780146"
          luau_file: "packages/mtc-artillery/scripts/exportProjectiles.luau"
          output_file: "${{ runner.temp }}/output.json"

      - name: Process JSON output
        run: jq ".[0]" "${{ runner.temp }}/output.json" > "packages/mtc-artillery/src/config/importedGuns.json"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "packages/mtc-artillery/src/config/importedGuns.json"
